// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1DxiTyB8g6fzNS5IM9owsNnaIdyaMjfE',
    appId: '1:599718942690:android:e706f4ade0c381dc9e8bbb',
    messagingSenderId: '599718942690',
    projectId: 'sewamitr-7adde',
    storageBucket: 'sewamitr-7adde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1DxiTyB8g6fzNS5IM9owsNnaIdyaMjfE',
    appId: '1:599718942690:ios:e706f4ade0c381dc9e8bbb',
    messagingSenderId: '599718942690',
    projectId: 'sewamitr-7adde',
    storageBucket: 'sewamitr-7adde.firebasestorage.app',
    iosBundleId: 'com.example.sewamitr',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX8FE8-1iGf4w-yikclsVo54F9u9Rm0Po',
    appId: '1:599718942690:web:2a64ae0438cda9ad9e8bbb',
    messagingSenderId: '599718942690',
    projectId: 'sewamitr-7adde',
    authDomain: 'sewamitr-7adde.firebaseapp.com',
    storageBucket: 'sewamitr-7adde.firebasestorage.app',
    measurementId: 'G-T7THYCTTRQ',
  );
}
